language: go
go:
- 1.7
before_install:
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
env:
  global:
    secure: dDtD4I4bEmLen/IKDe6FmF1WiaeVWdmaURq+6tJqQr3yG7zrnXB0xDWAWjby6TFibZMEnM+vSHnhot/TFJ74fw+uJsPRhWXNCT5Jf1nbQxGQxVtfGal8lxf+AbptXKzkaEedTtSQXeTsqfImCylAw7E+8J/wpxAJ5qtUZsH+vZ+3rvuUXLN7qMEpPa8APwTrUAgQklTnTR7IEk8LyZWJDS4VKdVVYk33u3x1e34YLPgIZCRMK3kb1uz7QTIeiJAVhN1LUVdpnH6OaQ6zFUkVl0//UdUXvCfCQhwKoaogsuHjO0oDB0rs9e0e/idsmfPUePf1Y5OEIWTFDc7l5h1ZMB0wwD3FYZD4qzcMFjs2raUFAt/P2vERJ/yDHgn7yqCQrDSJnfeGf97P4ZBe1btGzLyTgVtDYEUeKO1XoYx4/jkHnUg/+hc616B3eUbSO4KAjzoVYkv05JQ5jFUz/TluidUfoUEc2j5U5t6MtV6agOSbiYdE20JoVUxUnAtCaHkPQY4WZIXw1Y1U5W8EJ0L0XkY57sUCeypFNLZ4JzHExmxzOJxnWZaNZmk3vn8fq2OsHGMtiYEmvKZPQVpPUQCW4JIOD9dmQw8IGFzpBU0UTNiatojgN/C+mGqiJ4DcUCvssS1FqGMD4NzzqezSeWSdljDkgnf3B8dmJJB7CCkbqFE=
script:
- go get -d -t -v ./...
- go build -v ./...
- go test -cpu 4 -v ./...
- test -z "`gofmt -d .`"
- bash ./.travis/test-coverage.sh
