language: go
go:
- 1.7
before_install:
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
env:
  global:
  - secure: mUuzuulkya/YIiGMQes5CqJp5SKPH3nOxrUhJ5/KfLrVxlYVmc3yZxHie5CqocR06IXzlvmIzhAnmErAfySkWV29adFyZO/MKPheuPbwQ+kTNFtgtDYJnZVrdDShpKAQCI3keTVbtIedXQHa9hiAGqY4c/ColmsIsiDrgZeDXTUi2d2OMGtD/G0LOMNvPTJS466E3SYXU/65z6xYCv5I2Pz0C6bA6bmHDujMbEi/wjyqt0QFwghyuvCU/gcsOsx5B9VyV7XzaAXlZUB1Up6m8ck8qe1UV7DxjUg8MwQ5N0dY9rJFb6Ic+Ib1yHr4+1GQnOIVKvCH0siRC5wPS6e+RGbf5kWwpj+n8qzNAtsGjr9lUkG0AAsl7VVhRyKNzAxokXJqHRCp8orpYZSi1W3SmntV4kDbxz9W53P9Dd/4MigpkB2gIX+IM1g2LKjHXYllAoFCaS9RnflbtgY+4Corh0/yvtsSBpsVcYX67GTqkXg9y6lxlOyR2km/d+yN8hrdtYPqlnZJXo70MTv+XCiXloBb4UZFltCoDzrnvoc3g8jV1nr4NdDPHU9aL12/MiywhphA00qlQvKoqpYmJXXwWQWoZApDbqhU28P9kpdW93FMjuvlxsJd+fzyNyEr9wOH2Z6XGMNIJwVTTNGQhlc0FSnjhdYLN1xm7GOOCObIODQ=
script:
- go get -d -t -v ./...
- go build -v ./...
- go test -cpu 4 -v ./...
- test -z "`gofmt -d .`"
- bash ./.travis/test-coverage.sh
