// Code generated by protoc-gen-go.
// source: integrator.proto
// DO NOT EDIT!

/*
Package integrator is a generated protocol buffer package.

It is generated from these files:
	integrator.proto

It has these top-level messages:
	Query
	IntegralEstimate
	STPolynomial
	IntegralDefinition
*/
package integrator

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Compound query message
type Query struct {
	Poly *STPolynomial       `protobuf:"bytes,1,opt,name=poly" json:"poly,omitempty"`
	Def  *IntegralDefinition `protobuf:"bytes,2,opt,name=def" json:"def,omitempty"`
}

func (m *Query) Reset()                    { *m = Query{} }
func (m *Query) String() string            { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()               {}
func (*Query) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Query) GetPoly() *STPolynomial {
	if m != nil {
		return m.Poly
	}
	return nil
}

func (m *Query) GetDef() *IntegralDefinition {
	if m != nil {
		return m.Def
	}
	return nil
}

// Estimated integral return message
type IntegralEstimate struct {
	Result float64 `protobuf:"fixed64,1,opt,name=result" json:"result,omitempty"`
}

func (m *IntegralEstimate) Reset()                    { *m = IntegralEstimate{} }
func (m *IntegralEstimate) String() string            { return proto.CompactTextString(m) }
func (*IntegralEstimate) ProtoMessage()               {}
func (*IntegralEstimate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *IntegralEstimate) GetResult() float64 {
	if m != nil {
		return m.Result
	}
	return 0
}

// Single term polynomials are defined by their constants. I.e., -5x^3-43 is
// actually -5x^3+0x^2+0x^1-43X^0, which this message expresses as {Constants:
// []int32{-5, 0, 0, -43}}
type STPolynomial struct {
	Constants []int32 `protobuf:"zigzag32,1,rep,packed,name=constants" json:"constants,omitempty"`
}

func (m *STPolynomial) Reset()                    { *m = STPolynomial{} }
func (m *STPolynomial) String() string            { return proto.CompactTextString(m) }
func (*STPolynomial) ProtoMessage()               {}
func (*STPolynomial) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *STPolynomial) GetConstants() []int32 {
	if m != nil {
		return m.Constants
	}
	return nil
}

// Definit integral estimates are defined by the amount of strips we create
// under the curve and the start and end of the interval we measure the area
// of.
type IntegralDefinition struct {
	NumStrips int64   `protobuf:"varint,1,opt,name=numStrips" json:"numStrips,omitempty"`
	Start     float64 `protobuf:"fixed64,2,opt,name=start" json:"start,omitempty"`
	End       float64 `protobuf:"fixed64,3,opt,name=end" json:"end,omitempty"`
}

func (m *IntegralDefinition) Reset()                    { *m = IntegralDefinition{} }
func (m *IntegralDefinition) String() string            { return proto.CompactTextString(m) }
func (*IntegralDefinition) ProtoMessage()               {}
func (*IntegralDefinition) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *IntegralDefinition) GetNumStrips() int64 {
	if m != nil {
		return m.NumStrips
	}
	return 0
}

func (m *IntegralDefinition) GetStart() float64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *IntegralDefinition) GetEnd() float64 {
	if m != nil {
		return m.End
	}
	return 0
}

func init() {
	proto.RegisterType((*Query)(nil), "integrator.Query")
	proto.RegisterType((*IntegralEstimate)(nil), "integrator.IntegralEstimate")
	proto.RegisterType((*STPolynomial)(nil), "integrator.STPolynomial")
	proto.RegisterType((*IntegralDefinition)(nil), "integrator.IntegralDefinition")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Integrator service

type IntegratorClient interface {
	// Estimate the integral of the given single term polynomial at the given
	// interval.
	//
	// Accepts a message that defines the polynomial and the integral definition.
	// Returns the estimated value of the area under the curve.
	SingleTermPolynomialIntegral(ctx context.Context, in *Query, opts ...grpc.CallOption) (*IntegralEstimate, error)
}

type integratorClient struct {
	cc *grpc.ClientConn
}

func NewIntegratorClient(cc *grpc.ClientConn) IntegratorClient {
	return &integratorClient{cc}
}

func (c *integratorClient) SingleTermPolynomialIntegral(ctx context.Context, in *Query, opts ...grpc.CallOption) (*IntegralEstimate, error) {
	out := new(IntegralEstimate)
	err := grpc.Invoke(ctx, "/integrator.Integrator/SingleTermPolynomialIntegral", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Integrator service

type IntegratorServer interface {
	// Estimate the integral of the given single term polynomial at the given
	// interval.
	//
	// Accepts a message that defines the polynomial and the integral definition.
	// Returns the estimated value of the area under the curve.
	SingleTermPolynomialIntegral(context.Context, *Query) (*IntegralEstimate, error)
}

func RegisterIntegratorServer(s *grpc.Server, srv IntegratorServer) {
	s.RegisterService(&_Integrator_serviceDesc, srv)
}

func _Integrator_SingleTermPolynomialIntegral_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegratorServer).SingleTermPolynomialIntegral(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/integrator.Integrator/SingleTermPolynomialIntegral",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegratorServer).SingleTermPolynomialIntegral(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

var _Integrator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "integrator.Integrator",
	HandlerType: (*IntegratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SingleTermPolynomialIntegral",
			Handler:    _Integrator_SingleTermPolynomialIntegral_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "integrator.proto",
}

func init() { proto.RegisterFile("integrator.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x91, 0x41, 0x4b, 0x3b, 0x31,
	0x10, 0xc5, 0xff, 0xfb, 0x8f, 0x2d, 0x38, 0x7a, 0xd8, 0x0e, 0x22, 0x41, 0x16, 0x29, 0x39, 0x15,
	0x29, 0x45, 0xea, 0x57, 0xd0, 0x43, 0x6f, 0x36, 0xdb, 0x93, 0x17, 0x89, 0x36, 0x5d, 0x02, 0xd9,
	0x64, 0x49, 0x66, 0x0f, 0xfb, 0xed, 0x65, 0x53, 0xd7, 0x5d, 0xd0, 0xdb, 0xcc, 0xcb, 0x9b, 0xbc,
	0xcc, 0x2f, 0x90, 0x1b, 0x47, 0xba, 0x0a, 0x8a, 0x7c, 0xd8, 0x34, 0xc1, 0x93, 0x47, 0x18, 0x15,
	0x51, 0xc1, 0x6c, 0xdf, 0xea, 0xd0, 0xe1, 0x1a, 0x2e, 0x1a, 0x6f, 0x3b, 0x9e, 0x2d, 0xb3, 0xd5,
	0xd5, 0x96, 0x6f, 0x26, 0x53, 0xe5, 0xe1, 0xd5, 0xdb, 0xce, 0xf9, 0xda, 0x28, 0x2b, 0x93, 0x0b,
	0x1f, 0x81, 0x1d, 0xf5, 0x89, 0xff, 0x4f, 0xe6, 0xfb, 0xa9, 0x79, 0x77, 0x2e, 0xed, 0xb3, 0x3e,
	0x19, 0x67, 0xc8, 0x78, 0x27, 0x7b, 0xab, 0x78, 0x80, 0x7c, 0x38, 0x7a, 0x89, 0x64, 0x6a, 0x45,
	0x1a, 0x6f, 0x61, 0x1e, 0x74, 0x6c, 0x2d, 0xa5, 0xd4, 0x4c, 0x7e, 0x77, 0x62, 0x0d, 0xd7, 0xd3,
	0x4c, 0x2c, 0xe0, 0xf2, 0xd3, 0xbb, 0x48, 0xca, 0x51, 0xe4, 0xd9, 0x92, 0xad, 0x16, 0x72, 0x14,
	0xc4, 0x1b, 0xe0, 0xef, 0xd0, 0x7e, 0xc6, 0xb5, 0x75, 0x49, 0xc1, 0x34, 0x31, 0x5d, 0xcf, 0xe4,
	0x28, 0xe0, 0x0d, 0xcc, 0x22, 0xa9, 0x40, 0x69, 0x83, 0x4c, 0x9e, 0x1b, 0xcc, 0x81, 0x69, 0x77,
	0xe4, 0x2c, 0x69, 0x7d, 0xb9, 0x7d, 0x07, 0xd8, 0xfd, 0xec, 0x86, 0x7b, 0x28, 0x4a, 0xe3, 0x2a,
	0xab, 0x0f, 0x3a, 0xd4, 0xe3, 0xfb, 0x86, 0x74, 0x5c, 0x4c, 0x41, 0x24, 0xac, 0x77, 0xc5, 0x5f,
	0x6c, 0x06, 0x00, 0xe2, 0xdf, 0xc7, 0x3c, 0x7d, 0xc9, 0xd3, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x5f, 0xc4, 0x32, 0x54, 0xa6, 0x01, 0x00, 0x00,
}
